apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
    {{- include "testcm.app" . | indent 4 }}
data:
  drink: {{ .Values.favorite.drink | upper }}
  food: {{ .Values.favorite.food | upper }}

  {{- with .Values.favorite }}
  drink_with: {{ .drink | quote }}
  food_with: {{ .food | quote }}
  {{- end }}

